resolver: lts-7.10
packages:
  - '.'
  - location:
      git: https://github.com/lpeterse/haskell-socket.git
      commit: 6f135e01ecacfd01586146fc6187dae8776fe79f
extra-deps:
  - socket-0.8.0.0
  - QuickCheck-2.9.2
flags: {}
extra-package-dbs: []
